on:
  issue_comment:
    types: created
jobs:
  echo-timer:
    name: Cloud Echo Timer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo timer
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
